### ISSUE TITLE
[BUG] captureSession.stopRunning() Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by chase-robbins** [Mijick/Camera#43]
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/cc37bb74-cc25-4ba5-a349-b55233f7132e">

Steps to reproduce:
- Create SwiftUI Project
- Implement a TabView
- Implement MijickCameraView into one of the tabs
- Display tab with camera view, switch off, and return to tab with camera view
- App crashes

**Comment by ethan-crabb** [comment]
I'm facing the same problem using a NavigationStack. Were you able to find a workaround?

**Comment by chase-robbins** [comment]
> I'm facing the same problem using a NavigationStack. Were you able to find a workaround?

Nope. I migrated to this package instead. 

https://enebin.github.io/Aespa/documentation/aespa/

**Comment by jakub-kalamarz** [comment]
Guys, just don't declare manager in CameraView, you can inject it from parent.

**Comment by Bagmet-Denis** [comment]
when it is fixed i want to control the switch directly in the preview itself ?
