### ISSUE TITLE
[BUG] Camera View/Preview glitches in the UI when system call

### ISSUE THREAD

**Issue by clbemre** [Mijick/Camera#46]
@FulcrumOne Hello, how are you? :) 

When I am in Camera View or Camera Preview screen and a call comes to my phone, the UI gets corrupted and freezes. Can you check this?

Thank you.

**Comment by FulcrumOne** [comment]
Hey @clbemre,

I have tested this on iOS 18 and the problem does not appear there. Could you please give me more details? 

Thanks
