### ISSUE TITLE
[PERF] CPU usage is too high

### ISSUE THREAD

**Issue by gp1604** [Mijick/Camera#49]
i try it in iphone xsmax and 12pro is 120% cpu, and change camera not work. How can I fix it?

**Comment by FulcrumOne** [comment]
Hey @gp1604,

Thanks for the report. I'm aware of problems with compatibility the library with the newest iOS version. However, I'm physically not able to fix it, as I'm still busy with my other [library](https://github.com/Mijick/PopupView), that I plan to finish by the end of the month.

CameraView is the next one on my list, but unfortunately I can't start working on it prior to finalize the former one (I'm super sorry for this).

Have a good day,
T.K.

**Comment by FulcrumOne** [comment]
Hey @gp1604,

Could you try the `patch-2.1.1` branch and tell me if the problem is still there? I know it can happen if many filters are added (more than 5), but with a single, CPU it stays at ~20-30%, so acceptably.

Thanks!
