### ISSUE TITLE
[FREQ] Add option to change HDR mode during MCamera initialization

### ISSUE THREAD

**Issue by tiendq** [Mijick/Camera#68]
Don't know why I see this error while I checked `CameraManager.swift` and there is `hdrMode` option there.

<img width="853" alt="Screenshot 2024-12-09 at 11 53 59" src="https://github.com/user-attachments/assets/fc078cee-edb4-4ff1-952b-dcfa5fc8c0a7">

**Comment by FulcrumOne** [comment]
Hey @tiendq,

The problem should be fixed in the branch `patch-3.0.0`
