### ISSUE TITLE
[BUG] ErrorScreen is not shown when the user denies any of the required permissions

### ISSUE THREAD

**Issue by tiendq** [Mijick/Camera#73]
## Prerequisites
- [x] I checked the [documentation](https://github.com/Mijick/Camera/wiki) and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Default ErrorScreen is shown.

## Current Behavior

ErrorScreen is not shown when the user denies any of the required permissions, instead there was an exception:

```
(MijickCamera) ERROR DURING SETUP: cameraPermissionsNotGranted
MijickCamera/CameraManager+NotificationCenter.swift:35: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```
<img width="1226" alt="Screenshot 2024-12-16 at 11 08 15" src="https://github.com/user-attachments/assets/c93ec81a-2e44-4d44-926b-8d5d2591d48f" />

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.
1. Deny required permissions

| Name | Version |
| ------| ---------|
| SDK | e.g. 3.0.0 |
| Xcode | e.g. 16.0 |
| Operating System | e.g. iOS 17.1 |
| Device | e.g. iPhone 11 |

**Comment by FulcrumOne** [comment]
fixed in the branch `patch-3.0.1`
