### ISSUE TITLE
[BUG] Camera-Demo can not build

### ISSUE THREAD

**Issue by daozhonglee** [Mijick/Camera#75]
## Prerequisites
- [x] I checked the [documentation](https://github.com/Mijick/Camera/wiki) and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
Please describe the behavior you are expecting

## Current Behavior
i clone the https://github.com/Mijick/Camera-Demo and build it , But it prompts me with this error “Missing package product 'MijickCameraView'”

## Screenshots
![image](https://github.com/user-attachments/assets/4c20fa00-575c-4e46-92d9-5fbd16da73ae)

| Name | Version |
| ------| ---------|
| SDK | e.g. 3.0.0 |
| Xcode | e.g. 14.0 |
| Operating System | e.g. iOS 18.0 |
| Device | e.g. iPhone 14 Pro |

**Comment by FulcrumOne** [comment]
Hey @daozhonglee,

A working copy of this project can be found in the `beta` branch; the main branch is still not updated, as I'm working on the design of the demo project.

Sorry for the inconvenience,
Tomasz K.

**Comment by FulcrumOne** [comment]
@daozhonglee, the project has been updated ;)

**Comment by daozhonglee** [comment]
> @daozhonglee, the project has been updated ;)

thanks
